### ISSUE TITLE
Browser selections

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#102]
Change "Opera" to "Opera < v13 (Presto engine)"

Add the following browser:
Vivaldi

Also add the following choice:
App

Rename "IE" to "Internet Explorer"

**Comment by vbagirov** [comment]
There's a minor problem — browser names in this drop-down menu are hardcoded (except for `Other...`). It is possible, of course, to make them translatableб but not much reason to be honest.

We will make following changes:
`Opera` --> `Opera <13 (Presto)`
`IE` --> `Internet Explorer`

No need to add Vivaldi, I believe, as it falls into `Other...` category. 

No `App` option either since there's a separate tab for that. 

I'll close the issue for now.
