### ISSUE TITLE
Rename string

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#106]
"Please include names of other extensions or anti-virus software that you are using below, if there are any."

We should include some examples to extensions (... other extensions (e. g. hosts file modification, other adblock software)) as probably the user is running another adblocker like Ad Muncher along site it and with extensions the user may think only browser extensions are meant in this string.

**Comment by BooBerry** [comment]
Also in the reports generated, it'll list antivirus/antimalware apps under **Other extensions used:** - perhaps this should be split, one for extensions one for antivirus/antimalware so it's more clear?

**Comment by vbagirov** [comment]
I suggest changing the string to something like:
`Please list below names of other ad blocking extensions, anti-virus and firewall software etc. that you are using, if there are any.`

This way it becomes more clear what we want from users, but the sentence is not overcomplicated by examples etc.

As for *Other extensions used*, it's easier to rename this string rather than create a second one. E.g. *Other software used* or *Other software installed*, or your variant.

**Comment by vbagirov** [comment]
Done
