### ISSUE TITLE
Allow iOS users to report in-app ads

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/ReportsWebApp#143]
As of now, AG for iOS does not allow iOS users to report in-app ads under "Missed ads" or "Incorrect blocking" categories.

I think we might need to add the option to report App Store apps within these categories.

**Comment by lancelot-moon** [comment]
@ameshkov 

Yes, please give the option of ads in app as soon as possible!
I think that its priority is high.

<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/a60lyNw.png)

![image](https://i.imgur.com/Q5hed9T.png)

![image](https://i.imgur.com/8iJZHqb.png)
</details><br/>

Thanks.

**Comment by lancelot-moon** [comment]
Now, issues of ads in **different iOS apps** will be put under **the same topic**.
Ex:
https://github.com/AdguardTeam/AdguardFilters/issues/15645

Recently, I found that there is the option to report ads in iOS app from the English string on oneskyapp.
I think that you'll allow iOS users to report ads in iOS app in the near future.
Hope that you can let ads in different iOS apps be in different issues.
Ex: Ads in Android app.

Thanks.

**Comment by lancelot-moon** [comment]
@ameshkov 
It seems that the titles of any issues about ads in different iOS apps will only be "itunes.apple.com".
Ex: The issue is reported by another user.
He filled in the app link: https://itunes.apple.com/tw/app/id1102650114?mt=8
The title name is only "itunes.apple.com".
https://github.com/AdguardTeam/AdguardFilters/issues/18815

Is there other good method for the title name?
We should use different title names for ads in different iOS apps.

Thanks.
