### ISSUE TITLE
Add a simplified reports UI

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/ReportsWebApp#194]
Many users are complaining that the reporting process is very complicated, and they are unable to complete their report because of that.

The idea is to add something like an intro screen that offers to either pre-fill all information fields (without even displaying them to the user) or to switch to full reporting form where they can enter/edit any details manually.

**Comment by ameshkov** [comment]
But if you're sending the report from the program, everything is pre-filled already isn't it?

Save for the screenshots of course.

**Comment by akmLaVx** [comment]
You still have to click through everything, and it seems to either confuse the users or outright scare them. As I see it, we can just add a simplified reporting tool aimed at inexperienced / tech-illiterate users:

<details><summary>UI Mockup</summary>
![reportingTool-simple](https://user-images.githubusercontent.com/33634917/55755200-173c6780-5a57-11e9-83bc-5bf289e4608a.jpg)
</details>

**Comment by lancelot-moon** [comment]
Where is the comment?
The problem is that some users don't report issues via web reporting tool in AG apps.
So they need to manually fill in many information.

I often saw that users casually input wrong filters information.

The main problem is that most users don't want to report issues because of laziness.
The original one is already good.
Just need some minor improvements.
Even if simplifying it, it doesn't make sense.
Users who don't want to report never use it.
