### ISSUE TITLE
Under integration mode, the information of app name, version and configurations which are exported to web reporting tool should be AG for Windows/Mac's, not AG Browser Extension's.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/ReportsWebApp#232]
Under integration mode, filtering is controlled by AG for Windows/Mac.

Even if clicking `Submit a complaint about this website` in AG Browser Extension (integration mode), the information of app name, version and configurations which are exported to web reporting tool should be app name, version and configurations of AG for Windows/Mac, not AG Browser Extension's.

You'll give integration mode to new AG for Safari.
Please note, too.

**Comment by slavaleleka** [comment]
that's well known Integration mode issue. and since it is no longer supported by AdGuard Browser extension, there is no such issue anymore

for reporting the issue and other stuff you should use [AdGuard Browser Assistant](https://adguard.com/adguard-assistant/overview.html) which is developed for proper communication with standalone apps
