### ISSUE TITLE
Add some users identification

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/ReportsWebApp#79]
When one user create a lot of issues, there is a high probability that another users will not get a solution to their problem quickly.

**Comment by theBeautifier** [comment]
How about being not picky and solve the issues in chronological order so people won‘t have to wait up to or even more than 4 weeks? It‘s not that solving issues is just for that single person but for all AdGuard users. 
If a person wants to contribute to this great product by reporting issues because there is no other way to do so (e.g. pull requests being ignored or denied), what then justifies that these issues have to wait ages?

**Comment by Alex-302** [comment]
I can not process an issues of only a few users.

**Comment by ameshkov** [comment]
Calm down, the problem is not in people reporting issues, we simply need
more maintainers to handle all of them.

On Oct 30, 2017 12:49, "Alex" <notifications@github.com> wrote:

I can not process an issues of only a few users.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/ReportsWebApp/issues/79#issuecomment-340508182>,
or mute the thread

**Comment by Alex-302** [comment]
When user create 500 issues at once, it is equal to DDoS attack for me)

**Comment by ameshkov** [comment]
But it is not! Prioritizing the issues is a good idea anyway, but not based
on who reports it.

On Oct 30, 2017 12:51, "Alex" <notifications@github.com> wrote:

When user create 500 issues at once, it is equal to DDoS attack for me)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/AdguardTeam/ReportsWebApp/issues/79#issuecomment-340508945>,
or mute the thread
